music_extentions = [
    ".aac",
    ".aiff",
    ".dsf",
    ".flac",
    ".m4a",
    ".mp3",
    ".ogg",
    ".opus",
    ".wav",
    ".wv",
]

image_extentions = [".jpg", ".jpeg", ".png"]

playlist_extensions = [".m3u8"]

tag_keys = [
    "album",
    "albumartist",
    "artist",
    "artwork",
    "comment",
    "compilation",
    "composer",
    "discnumber",
    "genre",
    "lyrics",
    "totaldiscs",
    "totaltracks",
    "tracknumber",
    "tracktitle",
    "year",
    "isrc",
    "bitrate",
    "codec",
    "length",
    "channels",
    "bitspersample",
    "samplerat",
]

important_cols = [
    "Name",
    "Album",
    "Album Artist",
    "Artist",
    "Artwork Count",
    "Comment",
    "Compilation",
    "Composer",
    "Disc Number",
    "Genre",
    "Disc Count",
    "Track Count",
    "Track Number",
    "Year",
    "Persistent ID",
    "Bit Rate",
    "Kind",
    "Total Time",
    "Sample Rate",
]


tags_to_itunes_cols_dict = {
    "albumartist" : "Album Artist",
    "discnumber" : "Disc Number",
    "Total Discs": "Disc Count",
    "Total Tracks": "Track Count",
    "tracknumber" : "Track Number",
    "Track Title": "Name",
    "length": "Total Time",
    "codec": "Kind",
    'samplerat':'Sample Rate',
    "bitrate":"Bit Rate",
}

'Channels', 'Bitspersample', 'Samplerat',
       'Location', 'Album location'],


itunes_cols = [
    "Track ID",
    "Name",
    "Artist",
    "Album",
    "Genre",
    "Kind",
    "Size",
    "Total Time",
    "Disc Number",
    "Disc Count",
    "Year",
    "Date Modified",
    "Date Added",
    "Bit Rate",
    "Sample Rate",
    "Artwork Count",
    "Persistent ID",
    "Track Type",
    "Location",
    "File Folder Count",
    "Library Folder Count",
    "Album Artist",
    "Album Rating",
    "Compilation",
    "Composer",
    "Normalization",
    "Play Count",
    "Play Date",
    "Play Date UTC",
    "Podcast",
    "Rating",
    "Sort Album",
    "Sort Album Artist",
    "Sort Artist",
    "Sort Composer",
    "Sort Name",
    "Track Count",
    "Track Number",
    "Album Rating Computed",
    "BPM",
    "Clean",
    "Comments",
    "Content Rating",
    "Episode",
    "Episode Order",
    "Explicit",
    "Grouping",
    "HD",
    "Has Video",
    "Movement Count",
    "Movement Name",
    "Movement Number",
    "Part Of Gapless Album",
    "Purchased",
    "Release Date",
    "Season",
    "Series",
    "Skip Count",
    "Skip Date",
    "TV Show",
    "Unplayed",
    "Video Height",
    "Video Width",
    "Work",
]
